name: Thử nghiệm đọc file README #Tesst

on:
  push: 
    branches: [ "main" ]

jobs:
  thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      - name: Bước 1 - Xin chào
        run: echo "Hello CoCo"
      - name: Bước 2 - Tìm hiểu
        uses: actions/checkout@v6.0.2
      - name: Bước 3 - Đọc file
        run: cat README.md
